supervisor = """; Generated by Quilt at ${timestamp}
; Supervisor configuration to manage RQ for ${project_name}

[program:queue]
command=${project_env}/bin/python manage.py rqworker default
environment=PATH="${project_env}/bin"
directory=${project_root}
user=${user}
redirect_stderr=true
autostart=true
autorestart=true
"""

upstart = """# Generated by Quilt at ${timestamp}
# Upstart configuration to manage RQ for ${project_name}

author "${user}"
description "Manages RQ for ${project_name}"
start on starting ${project_name}
stop on stopping ${project_name}
respawn
console log
setuid ${user}
setgid ${user}
chdir ${project_root}
exec ${project_env}/bin/python manage.py rqworker default
"""
