user: robot
password:
key_filename:
roledefs:3
  app:
    - 127.0.0.1
  proxy:
    - 127.0.0.1
  cache:
    - 127.0.0.1
  queue:
    - 127.0.0.1
  db:
    - 127.0.0.1
use_ssh_config: true
forward_agent: true
workon:
deactivate: deactivate
project_name:
project_root:
project_env:
project_initial_data:
project_allowed_hosts:
project_cookie_domain:
project_packages:
project_secret_key:
project_config_file:
project_config_template:
proxy_config_file: /etc/nginx/nginx.conf
proxy_config_template: quilt.contrib.templates.nginx.config
proxy_management_file: /etc/supervisor/conf.d/proxy.conf
proxy_management_template: quilt.contrib.templates.nginx.supervisor
proxy_command_start: service nginx start
proxy_command_stop: service nginx stop
proxy_command_restart: service nginx restart
proxy_user: www-data
proxy_worker_connections: 1024
proxy_location: 127.0.0.1
proxy_port: 80
proxy_ssl_certificate:
proxy_ssl_certificate_key:
proxy_connection_scheme: http://
proxy_workers: 4
proxy_timeout: 30
proxy_accesslog:
proxy_errorlog:
app_config_file:
app_config_template: quilt.contrib.templates.gunicorn.config
app_management_file: /etc/supervisor/conf.d/app.conf
app_management_template: quilt.contrib.templates.gunicorn.supervisor
app_command_start: supervisorctl start app
app_command_stop: supervisorctl stop app
app_command_restart: supervisorctl restart app
app_command_update: supervisorctl update
app_location: 127.0.0.1
app_port: 8000
app_workers: 4
app_timeout: 30
app_instance:
app_accesslog:
app_errorlog:
queue_config_file:
queue_config_template: quilt.contrib.templates.celery.config
queue_management_file: /etc/supervisor/conf.d/queue.conf
queue_management_template: quilt.contrib.templates.celery.supervisor
queue_command_start: supervisorctl start queue
queue_command_stop: supervisorctl stop queue
queue_command_restart: supervisorctl restart queue
queue_command_update: supervisorctl update
queue_location: 127.0.0.1
queue_port: 8000
queue_broker: 127.0.0.1:6379/0
queue_backend: 127.0.0.1:6379/0
queue_max_cached_results: 5000
queue_accept_content: ['JSON']
queue_schedule:
queue_workers: 4
queue_instance:
queue_accesslog:
queue_errorlog:
db_config_file:
db_config_template:
db_management_file: /etc/supervisor/conf.d/db.conf
db_management_template: quilt.contrib.templates.postgres.supervisor
db_command_start: service start postgres
db_command_stop: service stop postgres
db_command_restart: service restart postgres
db_location: 127.0.0.1
db_port: 5432
db_user: robot
db_password:
db_dump_file:
cache_config_file:
cache_config_template:
cache_management_file: /etc/supervisor/conf.d/cache.conf
cache_management_template: quilt.contrib.templates.redis.supervisor
cache_command_start: service redis-server start
cache_command_stop: service redis-server stop
cache_command_restart: service redis-server restart
cache_location: 127.0.0.1
cache_port: 6379
cache_accesslog:
cache_errorlog:
email_user:
email_password:
repository_location:
repository_branch:
