config = """# Generated by Quilt at ${timestamp}
# Gunicorn configuration for ${project_name}

bind = '${app_location}:${app_port}'
workers = ${app_workers}
timeout = ${app_timeout}
access-logfile = ${app_accesslog}
error-logfile = ${app_errorlog}
# unlimited - we limit requests on the proxy server
limit-request-line = 0
"""

supervisor = """; Generated by Quilt at ${timestamp}
; Supervisor configuration to manage Gunicorn for ${project_name}

[program:app]
command=${project_env}/bin/gunicorn ${app_instance} --config ${app_config}
environment=PATH="${project_env}/bin"
directory=${project_root}
user=${user}
redirect_stderr=true
autostart=true
autorestart=true
"""

upstart = """# Generated by Quilt at ${timestamp}
# Upstart configuration to manage Gunicorn for ${project_name}

author "${user}"
description "Manages Gunicorn for ${project_name}"
start on (filesystem)
stop on runlevel [016]
respawn
console log
setuid ${user}
setgid ${user}
chdir ${project_root}
exec ${project_env}/bin/gunicorn ${app_instance} --config ${app_config}
"""
